apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctsedocker
  name: ctsedocker
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: ctsedocker
status:
  loadBalancer: {}